name: Terraform Apply and Output Load Balancer URL

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET }}
          AWS_DEFAULT_REGION: "us-east-1" # Replace with your AWS region

      - name: Output Load Balancer URL
        run: terraform output app_url > load_balancer_url.txt

      - name: Show Load Balancer URL
        run: cat load_balancer_url.txt
